POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
    "content": "ues",
    "important": "true"
}

###
GET http://localhost:3001/api/notes/

###
DELETE http://localhost:3001/api/notes/2

###
PUT http://localhost:3001/api/notes/6322f73847fca5c5547eed9c HTTP/1.1
content-type: application/json

{
    "content": "yesss",
    "important": "false"
}
###
DELETE http://localhost:3001/api/persons/63136bcf5ae76dfff29aa32e
###
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
    "name": "he",
    "number": "64"
}
###
GET http://localhost:3001/api/persons/

###
PUT http://localhost:3001/api/persons/63134617502ae3ea04122e13 HTTP/1.1
content-type: application/json

{
    "name": "ok",
    "number": "679"
}